### ISSUE TITLE
リストのアイテムの参照位置が未検出

### ISSUE THREAD

**Issue by Geson-anko** [Geson-anko/python-hydra-yaml#35]
# 不具合報告

## 概要

リストのアイテムの参照位置が未検出

<img width="554" alt="Image" src="https://github.com/user-attachments/assets/59071c9d-3265-479e-9417-465896976dd8" />

## 発生環境

hydra-yaml-lsp 0.1.1
VSCode: 0.4.4

## 再現手順

```yaml
environment:
  _target_: pamiq_vision_exp.envs.image_env.ImageEnvironment
  size:
  - ${shared.video.height}
  - ${shared.video.width}
```

## 修正しないとどう困るか

見にくい。正確に処理ができない。
