### ISSUE TITLE
Utils: `get_current_yaml_block`をラップし、indentを削除したyaml linesを返す関数を実装

### ISSUE THREAD

**Issue by Geson-anko** [Geson-anko/python-hydra-yaml#4]
# タスク

補完の際に、現在のyamlブロックのindentや `- `を削除する必要があって面倒なので、それをcleanup した値を返す関数を実装します

## 仕様

yamlブロックのlineを受け取り、 先頭のスペースおよび `- ` を削除します。

```yaml
  - aaa: 0
     bbb: 1
     ccc: 2
```

を入力したら、

```yaml
aaa: 0
bbb: 1
ccc: 2
```
として返します。

## リファクタリング

既存のいくつかの補完機能もこのcleanupを使うと簡潔に書くことができるので、`get_current_yaml_block`の参照を探してリファクタリングもします。
